#!/bin/bash
# A start script for Polybar panel
# Based on script found on Archlinux Wiki
# Added by Mr Green [mrgreen@archbang.org]

# Terminate already running bar instances
killall -q polybar
# If all your bars have ipc enabled, you can also use
# polybar-msg cmd quit

# Launch Polybar, using default config location ~/.config/polybar/config.ini
polybar archbang 2>&1 | tee -a /tmp/polybar.log & disown

echo "Polybar launched..."
