#!/usr/bin/env bash
# Script to start Polybar panel
# modified for GreenBang 
# by Mr Green [mrgreen@archbang.org]

# Terminate already running bar instances
killall -q polybar

# Launch Polybar
polybar greenbang 2>&1 | tee -a /tmp/polybar.log & disown

echo "Polybar launched..."
