#!/bin/sh

# Restart NetworkManager (ensure it's fully initialized)
doas rc-service networkmanager restart &

# Update D-Bus environment for Wayland session
dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# Set wallpaper
swaybg -i $HOME/Backgrounds/seafront.jpg -m fill &

# Start waybar
waybar &

# Notification daemon
mako &

# Network manager applet
nm-applet &

# System monitor
conky &
